name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  php-cs:
    name: PHP CS
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run PHP CS
        run: ./vendor/bin/phpcs --parallel=4 -s
